{% set name = "tethys_dataset_services" %}
{% set version = "2.4.1" %}
{% set python_min = "3.10.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 126a7d4daf856f980b70ad628bb0e660400eb12557c76d9e3abc3a1bfcd45850

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django
    - future
    - jinja2
    - owslib
    - geoserver-restconfig
    - requests
    - requests-toolbelt
    - sqlalchemy <2
    - psycopg2
    - psycopg2-binary

test:
  imports:
    - tethys_dataset_services
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/tethysplatform/tethys_dataset_services
  summary: A generic Python interface for dataset services such as GeoServer, CKAN, and HydroShare
  description: |
    Tethys datasets provides a Python API for various 
    dataset services such as GeoServer, CKAN, and HydroShare.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: http://docs.tethysplatform.org/en/stable/tethys_sdk/tethys_services/spatial_dataset_services.html#spatial-dataset-engine-references
  dev_url: https://github.com/tethysplatform/tethys_dataset_services

extra:
  recipe-maintainers:
    - swainn
